name: Build
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_dispatch: # This allows this workflow to be called from another workflow
    

jobs:
  build-kernel-oneplus-kernelsu-susfs:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup System
        run: |
          export DEBIAN_FRONTEND=noninteractive
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
          
          df -h
          
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
          sudo docker image prune --all --force
          echo "some directories deleted"
          
          # Remove large unwanted packages
          sudo apt-get purge -y \
            aria2 ansible azure-cli shellcheck rpm xorriso zsync \
            firefox gfortran-9 google-chrome-stable \
            google-cloud-sdk imagemagick \
            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
            mercurial apt-transport-https mono-complete \
            unixodbc-dev yarn chrpath libxft-dev \
            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
            sphinxsearch subversion microsoft-edge-stable || true
            
          # Regex-based purges (for bulk families like mysql, php, dotnet)
          sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
          
          # Clean up
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          echo "some packages purged"
          
          df -h

      - uses: actions/checkout@v4

      - name: Set CONFIG Environment Variable
        run: |
          CONFIG="OP9"
          echo "Creating folder for configuration: $CONFIG..."
          mkdir -p "$CONFIG"
          
          # Set CONFIG as an environment variable for future steps
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
          
          echo "CONFIG set to: $CONFIG"

      - name: Install Repo and Python
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache python3
          sudo apt-get install -y pngcrush schedtool dpkg-dev liblz4-tool make optipng maven device-tree-compiler 
          sudo apt-get install -y libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc
          sudo apt-get install -y libxml2-utils libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools lzop flex tree 
          sudo apt-get install -y pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl 
          sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar llvm g++-multilib bison gperf zlib1g-dev automake
          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev binutils-aarch64-linux-gnu
          
          mkdir -p "${{ env.CONFIG }}/git-repo"
          curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > "${{ env.CONFIG }}/git-repo/repo"
          chmod a+rx "${{ env.CONFIG }}/git-repo/repo"
          echo "REPO=${{ github.workspace }}/${{ env.CONFIG }}/git-repo/repo" >> $GITHUB_ENV

      - name: Initialize and Sync Kernel Source
        run: |
          cd "$CONFIG"
          
          # Initialize and sync kernel source
          echo "Initializing and syncing kernel source..."
          $REPO init -u https://github.com/xiakehelper/BUILD_OP9_KERNEL.git -b main -m manifest.xml --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
          
          # Sync repo and apply patches
          $REPO --trace sync -c --no-clone-bundle --no-tags --optimized-fetch -j$(nproc --all) --fail-fast

          set -x
          echo "${{ github.workspace }}/${{ env.CONFIG }}/prebuilts/clang/host/linux-x86/clang-r416183b/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/${{ env.CONFIG }}/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/${{ env.CONFIG }}/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin" >> $GITHUB_PATH

      - name: Add SYSTEM Configuration Settings
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG/kernel/msm-5.4"
          
          echo "Adding configuration settings to gki_defconfig..."

          #Add Docker config setting
          # 2.1
          echo "CONFIG_HOLES_IN_ZONE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_HZ_250=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_HZ=250" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_SCHED_HRTICK=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_SUPPORTS_DEBUG_PAGEALLOC=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_SPARSEMEM_ENABLE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_SPARSEMEM_DEFAULT=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_SELECT_MEMORY_MODEL=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_FLATMEM_ENABLE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_HAVE_ARCH_PFN_VALID=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_HW_PERF_EVENTS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_SYS_SUPPORTS_HUGETLBFS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_WANT_HUGE_PMD_SHARE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_HAS_CACHE_LINE_SIZE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_ENABLE_SPLIT_PMD_PTLOCK=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CC_HAVE_SHADOW_CALL_STACK=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_FORCE_MAX_ZONEORDER=11" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_UNMAP_KERNEL_AT_EL0=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_MITIGATE_SPECTRE_BRANCH_HISTORY=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_RODATA_FULL_DEFAULT_ENABLED=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_TAGGED_ADDR_ABI=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_KUSER_HELPERS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_COMPAT_VDSO=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_THUMB2_COMPAT_VDSO=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_HW_AFDBM=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_PAN=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_AS_HAS_LDAPR=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_AS_HAS_LSE_ATOMICS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_LSE_ATOMICS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_USE_LSE_ATOMICS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_VHE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_UAO=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_RAS_EXTN=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_CNP=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_PTR_AUTH=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CC_HAS_BRANCH_PROT_PAC_RET=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CC_HAS_SIGN_RETURN_ADDRESS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_AS_HAS_PAC=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_AS_HAS_CFI_NEGATE_RA_STATE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_AMU_EXTN=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_AS_HAS_ARMV8_4=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_TLB_RANGE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_AS_HAS_ARMV8_5=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_BTI=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_BTI_KERNEL=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CC_HAS_BRANCH_PROT_PAC_RET_BTI=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_E0PD=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_RANDOM=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_AS_HAS_MTE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_MTE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_SVE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM64_MODULE_PLTS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_RELOCATABLE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CMDLINE=\"ignore_loglevel\"" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_STUB=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_BUILD_ARM64_KERNEL_COMPRESSION_GZIP=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_BUILD_ARM64_DT_OVERLAY=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_ENABLE_HUGEPAGE_MIGRATION=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_ENABLE_THP_MIGRATION=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_SUSPEND=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_SUSPEND_FREEZER=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_SLEEP=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_SLEEP_SMP=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_CLK=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_GENERIC_DOMAINS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_GENERIC_DOMAINS_SLEEP=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_GENERIC_DOMAINS_OF=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_PM=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_HIBERNATION_POSSIBLE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARCH_SUSPEND_POSSIBLE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_IDLE_MULTIPLE_DRIVERS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_IDLE_GOV_MENU=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_IDLE_GOV_TEO=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_DT_IDLE_STATES=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM_PSCI_CPUIDLE_DOMAIN=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_GOV_ATTR_SET=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_GOV_COMMON=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_GOV_PERFORMANCE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM_QCOM_CPUFREQ_HW=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_QTI_SCMI_PMU_PROTOCOL=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_QTI_SCMI_C1DCVS_PROTOCOL=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_QTI_SCMI_PLH_PROTOCOL=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_QTI_SCMI_GPLAF_PROTOCOL=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_QCOM_SCM=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_QTEE_SHM_BRIDGE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_ESRT=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_VARS_PSTORE=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_PARAMS_FROM_FDT=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_RUNTIME_WRAPPERS=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_GENERIC_STUB=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_GENERIC_STUB_INITRD_CMDLINE_LOADER=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_EFI_EARLYCON=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM_PSCI_FW=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_HAVE_ARM_SMCCC=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_HAVE_ARM_SMCCC_DISCOVERY=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_ARM_SMCCC_SOC_ID=y" >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_QTI_TZ_LOG=y" >> ./arch/arm64/configs/gki_defconfig

          
      - name: Run sed and perl Commands
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG/kernel/msm-5.4"
          
          echo "Running sed commands..."
          
          sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' "./arch/arm64/configs/gki_defconfig"
          sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "./arch/arm64/configs/gki_defconfig"
          sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "./arch/arm64/configs/gki_defconfig"
          
          # Run sed commands for modifications
          sed -i 's/check_defconfig//' ./build.config.gki
          sed -i '$s|echo "\$res"|echo "\$res-xiakehelper"|' ./scripts/setlocalversion
          sed -i 's/-dirty//' ./scripts/setlocalversion
         
          # Run perl command to modify UTS_VERSION
          perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Thu Mar 05 04:20:00 UTC 2025"}' ./scripts/mkcompile_h

      - name: GCC Build
        run: |
          cd "$CONFIG"
          sed -i s/build-user/xiakehelper/g build/_setup_env.sh
          sed -i s/build-host/oos/g build/_setup_env.sh
          cp $GITHUB_WORKSPACE/build.config.lemonadep ./kernel/msm-5.4/build.config.lemonadep
          patch -p1 -F 3 < $GITHUB_WORKSPACE/Patches/fix_op9p_build_errors.patch
          patch -p1 --binary -F 3 < $GITHUB_WORKSPACE/Patches/si_audo_codec_build.patch
          sed -i 's/^UAPI_CFLAGS :=.*/& -Wno-gnu-variable-sized-type-not-at-end/' ./kernel/msm-5.4/usr/include/Makefile
          
          
          # Export variables for immediate use in the shell
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export ARCH=arm64
          export SUBARCH=arm64
          
          # Append variables to $GITHUB_ENV for GitHub Actions
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          
          # Export build configuration variables
          export BUILD_CONFIG=kernel/msm-5.4/build.config.lemonadep
          export VARIANT=qgki
          export BUILTIN=1
          export LTO=thin
          export POLLY=1
          export GRAPHITE=1
          export PGO=1
          export SKIP_MRPROPER=1
          export BUILD_KERNEL=1
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          export LD=ld.lld
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJSIZE=llvm-size
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export READELF=llvm-readelf
          export STRIP=llvm-strip
          export LLVM_AR=llvm-ar
          export LLVM_DIS=llvm-dis
          export LDGOLD=aarch64-linux-gnu-ld.gold
          export LLVM=1
          export LLVM_IAS=1
          # export AS=aarch64-linux-gnu-as
          
          # Append build configuration variables to $GITHUB_ENV
          echo "BUILD_CONFIG=kernel/msm-5.4/build.config.lemonadep" >> $GITHUB_ENV
          echo "VARIANT=qgki" >> $GITHUB_ENV
          echo "BUILTIN=1" >> $GITHUB_ENV
          echo "LTO=thin" >> $GITHUB_ENV
          echo "POLLY=1" >> $GITHUB_ENV
          echo "GRAPHITE=1" >> $GITHUB_ENV
          echo "PGO=1" >> $GITHUB_ENV
          echo "SKIP_MRPROPER=1" >> $GITHUB_ENV
          echo "BUILD_KERNEL=1" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-android-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_ARM32=arm-linux-androideabi-" >> $GITHUB_ENV
          echo "LD=ld.lld" >> $GITHUB_ENV
          echo "AR=llvm-ar" >> $GITHUB_ENV
          echo "NM=llvm-nm" >> $GITHUB_ENV
          echo "OBJSIZE=llvm-size" >> $GITHUB_ENV
          echo "OBJCOPY=llvm-objcopy" >> $GITHUB_ENV
          echo "OBJDUMP=llvm-objdump" >> $GITHUB_ENV
          echo "READELF=llvm-readelf" >> $GITHUB_ENV
          echo "STRIP=llvm-strip" >> $GITHUB_ENV
          echo "LLVM_AR=llvm-ar" >> $GITHUB_ENV
          echo "LLVM_DIS=llvm-dis" >> $GITHUB_ENV
          echo "LDGOLD=aarch64-linux-gnu-ld.gold" >> $GITHUB_ENV
          echo "LLVM=1" >> $GITHUB_ENV
          echo "LLVM_IAS=1" >> $GITHUB_ENV
          # echo "AS=aarch64-linux-gnu-as" >> $GITHUB_ENV
          
          LLVM=1 LLVM_IAS=1 build/build.sh -j4

      - name: Create zip
        run: |
          cd "$CONFIG"
          mkdir MyKernel
          chmod 777 MyKernel
          cp out/msm-5.4-lahaina-qgki/dist/Image MyKernel/
          cd MyKernel/ && zip -r9 OP9P-$(/bin/date -u '+%d%m%Y%I%M')-clang.zip * -x .git README.md ./*/placeholder
          cd ../

      - name: Archive Kernel Source
        if: always()
        run: |
          cd "$CONFIG"
          tar -czf kernel-source.tar.gz --exclude='.git' --exclude='out' --warning=no-file-changed ./kernel ./vendor
          ls -la

      - name: Upload Kernel Source Archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-source-archive
          path: ${{ env.CONFIG }}/kernel-source.tar.gz
          retention-days: 7

      - uses: actions/upload-artifact@main
        with:
         name: "lemonadep-ksun-release-${{ env.KSUNVER }}-zip"
         path: ${{ env.CONFIG }}/MyKernel/*.zip
